theme: jekyll-theme-cayman
google_analytics: UA-xxxxxx-x
plugins:
  - jekyll-sitemap
url: https://Reonagasawa86.github.io/new
root: /{new}
permalink: :year/:month/:day/:title/
permalink_defaults:

deploy:
  type: git
  repository: {}
  branch: gh-page
